import type { ScheduleData } from "@/types/schedule"

export const sampleScheduleData: ScheduleData = {
  allEntries: [
    {
      jobName: "MODERN MASONRY",
      truckType: "Slinger",
      pit: "SM-WB",
      shift: "Scheduled",
      truckDriver: "SMI95S",
      date: "07/28/2025",
      time: "14:00",
      showUpTime: "13:45",
      location: "9560 BIG TREE RD, HEMLOCK, N.Y.",
      qty: "1: LD",
      materials: "Crushed 1's per Ton",
      notes: "",
      numTrucks: "1",
      interval: "0",
      showUpOffset: "15",
    },
    {
      jobName: "MORRELL BLDRS",
      truckType: "Slinger",
      pit: "SM-WB",
      shift: "Scheduled",
      truckDriver: "SMI95S",
      date: "07/28/2025",
      time: "12:00",
      showUpTime: "11:45",
      location: "LOTS 22 & 23 PIERCEBROOK EST., CANANDAIGUA, N.Y.",
      qty: "2: LD",
      materials: "Crushed 1's per Ton",
      notes: "",
      numTrucks: "1",
      interval: "0",
      showUpOffset: "15",
    },
    {
      jobName: "G4 CONSTRUCTION",
      truckType: "Dump Truck",
      pit: "SM-WB",
      shift: "Scheduled",
      truckDriver: "TBD",
      date: "07/28/2025",
      time: "14:00",
      showUpTime: "14:00",
      location: "9 COLDWATER CRESCENT, ROCHESTER, N.Y.",
      qty: "14: YD",
      materials: "Mason per CY",
      notes: "",
      numTrucks: "1",
      interval: "0",
      showUpOffset: "15",
    },
    {
      jobName: "WASTE MGT/HIGH ACRES",
      truckType: "Trailer",
      pit: "SM-OAKS",
      shift: "1st",
      truckDriver: "SMI114",
      date: "07/28/2025",
      time: "07:00",
      showUpTime: "06:45",
      location: "PERINTON PARKWAY, FAIRPORT, N.Y.",
      qty: ": LD",
      materials: "Crushed 2's per TN",
      notes: "",
      numTrucks: "1",
      interval: "0",
      showUpOffset: "15",
    },
  ],
  byTruckType: {
    Slinger: [
      {
        jobName: "MODERN MASONRY",
        truckType: "Slinger",
        pit: "SM-WB",
        shift: "Scheduled",
        truckDriver: "SMI95S",
        date: "07/28/2025",
        time: "14:00",
        showUpTime: "13:45",
        location: "9560 BIG TREE RD, HEMLOCK, N.Y.",
        qty: "1: LD",
        materials: "Crushed 1's per Ton",
        notes: "",
        numTrucks: "1",
        interval: "0",
        showUpOffset: "15",
      },
      {
        jobName: "MORRELL BLDRS",
        truckType: "Slinger",
        pit: "SM-WB",
        shift: "Scheduled",
        truckDriver: "SMI95S",
        date: "07/28/2025",
        time: "12:00",
        showUpTime: "11:45",
        location: "LOTS 22 & 23 PIERCEBROOK EST., CANANDAIGUA, N.Y.",
        qty: "2: LD",
        materials: "Crushed 1's per Ton",
        notes: "",
        numTrucks: "1",
        interval: "0",
        showUpOffset: "15",
      },
    ],
    "Dump Truck": [
      {
        jobName: "G4 CONSTRUCTION",
        truckType: "Dump Truck",
        pit: "SM-WB",
        shift: "Scheduled",
        truckDriver: "TBD",
        date: "07/28/2025",
        time: "14:00",
        showUpTime: "14:00",
        location: "9 COLDWATER CRESCENT, ROCHESTER, N.Y.",
        qty: "14: YD",
        materials: "Mason per CY",
        notes: "",
        numTrucks: "1",
        interval: "0",
        showUpOffset: "15",
      },
    ],
    Trailer: [
      {
        jobName: "WASTE MGT/HIGH ACRES",
        truckType: "Trailer",
        pit: "SM-OAKS",
        shift: "1st",
        truckDriver: "SMI114",
        date: "07/28/2025",
        time: "07:00",
        showUpTime: "06:45",
        location: "PERINTON PARKWAY, FAIRPORT, N.Y.",
        qty: ": LD",
        materials: "Crushed 2's per TN",
        notes: "",
        numTrucks: "1",
        interval: "0",
        showUpOffset: "15",
      },
    ],
  },
}
